### ISSUE TITLE
Drum-Machine

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#1]
## Value proposition

**As a User**
**I need to have 16 buttons**
**to be able to play some music**

## Description
![Bildschirmfoto 2022-03-03 um 11 36 34](https://user-images.githubusercontent.com/95469432/156547969-6c08be86-af81-4edb-83fe-79425502359a.png)

## Acceptance Criteria

- [ ] Each button should play a Sound if get clicked

## Tasks

- [ ] Create -> components/DrumMachine
- [ ] Add Global-Styles
- [ ] Add Storybook
- [ ] Write tests
- [ ] Check accessibility
- [ ] Add to App
