### ISSUE TITLE
Drum-Machine

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#1]
## Value proposition

**As a** User
**I need to** have 12 buttons
**to be able** to play some music

## Description
<img width="296" alt="Bildschirmfoto 2022-03-04 um 23 38 46" src="https://user-images.githubusercontent.com/95469432/156851523-becbd8f6-219d-48a7-84b4-10d4995699f5.png">

## Acceptance Criteria

- [x] Each button should play a Sound if get clicked

## Tasks

- [x] Add Global-Styles
- [x] Create -> pages/DrumMachine
     - [x] Add Storybook
     - [x] Write tests
- [x] - [ ] Create -> components/DrumPad
     - [x] Add Storybook
     - [x] Write tests
- [x] Check accessibility
- [x] Add to App
- [x] Test on mobile device
