### ISSUE TITLE
Add-recording-function

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#10]
## Value proposition

**As a** User
**I need** a record button
**to be able to** record and download my sounds

## Description
<img width="247" alt="Bildschirmfoto 2022-03-17 um 12 00 34" src="https://user-images.githubusercontent.com/95469432/158795375-95e6df1f-b19b-43d3-a07d-3048f86d0b04.png">

## Acceptance Criteria

- [x] The User should be able to record the sounds by click on the record button
- [x] After the second click the record should be stopped
- [x] After stopping the recording, the User should be able to hear and download the record in a audio-player

## Tasks
- [x] Create -> components/Recording
     - [x] Add function to record the sounds
     - [x] Add a audio-player to hear and download your recording
- [x] Add Recording to the DrumMachinePage
- [x] Write tests
- [x] Check accessibility
- [x] Check on mobile device
