### ISSUE TITLE
Local-Storage

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#11]
## Value proposition

**As a** User
**I want** my settings to be saved
**to be able to** get the same settings again

## Description
Add Local Storage to save the Settings of the User

## Acceptance Criteria

- [ ] After changing the Settings should be saved automaticly in the Local Storage
- [ ] After reload the Settings should load automaticly from the Local Storage

## Tasks

- [ ] Add function to save settings in the Local Storage
- [ ] Add function to load settings from the Local Storage
- [ ] Check on mobile device
