### ISSUE TITLE
Add-Settings-Preview

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#13]
## Value proposition

**As a** User
**I need** a preview of the colors and a prieview of the new sample
**to be able to** see the new color combination and hear the new sample

## Description
<img width="253" alt="Bildschirmfoto 2022-03-12 um 16 01 23" src="https://user-images.githubusercontent.com/95469432/158023336-5b448e4c-d050-4d1c-b979-8708ed207a00.png">

## Acceptance Criteria

- [ ] There is a little preview with all DrumPads and their numbers
- [ ] There is a button which plays a preview of the selected sample 

## Tasks

- [ ] Add 12 buttons on SettingsPage
- [ ] Add a play button SettingsPage
- [ ] Update tests
- [ ] Check accessibility
- [ ] Check on mobile device
