### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#14]
## Value proposition

**As a** User
**I need** Keyboard
**to be able to** play tones at different pitches

## Description
<img width="629" alt="Bildschirmfoto 2022-03-13 um 19 32 33" src="https://user-images.githubusercontent.com/95469432/158074016-064b85a3-20e6-4bb2-8fb2-1676d432d3b7.png">

## Acceptance Criteria

- [ ] At orientation landscape: A Keyboard is shown with buttons which plays a sound of a synthesizer
- [ ] Each button plays a different pitch
- [ ] At orientation portrait: The DrumMachine is shown

## Tasks

- [ ] Create -> pages/KeyboardPage
     - [ ] Create 24 Buttons
     - [ ] Add the function to play the synth sound
     - [ ] Add DrumLoopPlayer to the KeyBoardPage
- [ ] Update styling
- [ ] Add to App
- [ ] Check accessibility
- [ ] Check on mobile devices
