### ISSUE TITLE
Sequencer

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#17]
## Value proposition

**As a** User
**I need** a Sequencer Page
**to be able to** insert my samples in a timeline

## Description
<img width="699" alt="Bildschirmfoto 2022-03-15 um 11 03 18" src="https://user-images.githubusercontent.com/95469432/158354065-e72b4612-6abd-489f-99e8-6c90424976cc.png">

## Acceptance Criteria

- [x] There is a new SequencerPage
- [x] There are 12 buttons that can be selected with a click
- [x] There is a timeline in which the selected button can be placed
- [x] The assigned sample of the button should only be played at the placed location

## Tasks

- [x] Create -> pages/SequencerPage
     - [x] Add route to App
     - [x] Add 12x Drumpad to SequencerPage
     - [x] Add NavLink back to DrumMachine
- [x] Create -> components/SequencerPad
     - [x] Add functionality
- [x] Create -> components/SequencerTimeline        
     - [x] Add the Sequencer functionality 
- [x] Add storybook
- [x] Add tests
- [x] Check accessibility
- [x] Check on mobile device
