### ISSUE TITLE
Drum-Pad lighting up

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#2]
## Value proposition

**As a** User
**I want to** see the Drum-Pad is lighting up on click
**in order to** get a feedback on a click

## Description
<img width="285" alt="Bildschirmfoto 2022-03-04 um 23 41 51" src="https://user-images.githubusercontent.com/95469432/156851812-33d6fa7e-9ec4-4653-bf99-68304329be2c.png">

## Acceptance Criteria

- [x] The Drum-Pad is lighting up on a click

## Tasks

- [x] Add effect on the Drum-Pads while they are active
- [x] Check on mobile device
