### ISSUE TITLE
record-page

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#20]
## Value proposition

**As a** User
**I need** a RecordingsPage
**to be able to** hear all my last recordings.

## Description
<img width="521" alt="Bildschirmfoto 2022-03-18 um 09 25 59" src="https://user-images.githubusercontent.com/95469432/158964104-d39e1791-81ff-41c8-952d-599395b5cf49.png">

## Acceptance Criteria

- [x] There is a new RecordingsPage
- [x] There is a list with the last recordings
- [x] The user should be able to hear and download the last recordings

## Tasks

- [x] Create -> pages/RecordingsPage
     - [x] Add a list for all recordings
     - [x] Map all recordings in this list
     - [x] Add a Route to App
     - [x] Add RecordingsPage to App
- [x] Add a NavLink to DrumMachinePage
- [x] Check accessibility
- [x] Check on mobile device
