### ISSUE TITLE
volume-control

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#22]
## Value proposition

**As a** User
**I need** a volume control
**to be able to** set the perfect volume to my devices

## Description
<img width="741" alt="Bildschirmfoto 2022-03-20 um 11 22 19" src="https://user-images.githubusercontent.com/95469432/159158029-2fc454a0-996f-4c8a-8a27-7b91d1b0ef67.png">

## Acceptance Criteria

- [ ] There is a volume control on the KeyboardPage which changes the volume of the Keyboard
- [ ] There is a new button on DrumMachinePage which opens the volume controls
     - [ ] The volume must be changeable 
     - [ ] After a second click on the button, the volume control must disappear again 

## Tasks

- [ ] Add the volume control to the KeyboardPage
- [ ] Add a button on DrumMachinePage which opens/close the volume control after a click
- [ ] Create -> components/VolumeControl
     - [ ] Add volume functionality
     - [ ] Write tests
     - [ ] Add Storybook
- [ ] Check accessibility
- [ ] Check on mobile device
