### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#23]
## Value proposition

**As a** User
**I need** instructions
**to understand** how the app works

## Description
<img width="789" alt="Bildschirmfoto 2022-03-20 um 12 47 10" src="https://user-images.githubusercontent.com/95469432/159160882-497f1675-a2b9-4c00-b403-cbbcdb5d4fd8.png">

## Acceptance Criteria

- [x] After loading of the website, a small window will appear to get to the instructions
- [x] After clicking on "X" the small window should disappear
- [x] After clicking on "click here for instructions" the User should get a instruction of the app

## Tasks

- [x] Add a modal that only is shown on the first loading of the website
- [x] Add a button that removes the modal and a button that starts the instructions
- [x] Add a Button to stop the instructions and a button to get to the next instruction
- [x] Add the instruction functionality
- [x]  Check accessibility
- [x] Check on mobile device
