### ISSUE TITLE
Sequncer-bpm

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#24]
## Value proposition

**As a** User
**I need** a bpm control
**to be able to** change the speed of the sequencer

## Description

<img width="240" alt="Bildschirmfoto 2022-03-24 um 16 20 08" src="https://user-images.githubusercontent.com/95469432/159950352-f786ce23-ff61-41f3-a82c-b45792460121.png">

## Acceptance Criteria

- [x] There is a new input on the SequencerPage which change the speed of the sequencer

## Tasks

- [x] Create -> components/SequencerSettings
- [x] Add input to change the speed
- [x] Write tests
- [x] Add Storybook
- [x] Check on mobile device
- [x] Check accessibility
