### ISSUE TITLE
framer-motion

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#25]
## Value proposition

**As a** User
**I want** interesting effects
**to have desire to** visit the website again

## Description
<img width="614" alt="Bildschirmfoto 2022-03-20 um 18 08 32" src="https://user-images.githubusercontent.com/95469432/159174260-3f03e38a-4723-49ed-ba08-192de957b8f3.png">

## Acceptance Criteria

- [x] After loading of the website, the elements fly to their place over a short period of time 

## Tasks

- [x] Add framer-motion styling
- [x] Check accessibility
- [x] Check on mobile device
