### ISSUE TITLE
Drum-Loop

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#3]
## Value proposition

**As a** User
**I need a** background sound / drum loop
**in order to** drum together with the drum-loop

## Description
<img width="278" alt="Bildschirmfoto 2022-03-04 um 23 43 23" src="https://user-images.githubusercontent.com/95469432/156851987-ab47377a-ea94-4e25-98a9-5790d1219cac.png">

## Acceptance Criteria

- [x] There is a dropdown menu with default Drum-Loops
- [x] After click on play the chosen Drum-Loop should played

## Tasks

- [x] Create -> components/DrumLoopPlayer
     - [x] Add a dropdown menu with prefilled Drum-Loops
     - [x] Create a Play-Button which plays the chosen Drum-Loop
     - [x] Add to DrumMachinePage
     - [x] Write tests
     - [x] Add to storybook
- [x] Check on mobile devices
- [x] Check accessibility
