### ISSUE TITLE
landingpage

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#32]
## Value proposition

**As a** User
**I need** a landingpage
**to be able to** get a instruction or get to the device of my choice

## Description
<img width="291" alt="Bildschirmfoto 2022-03-27 um 22 39 36" src="https://user-images.githubusercontent.com/95469432/160300221-7ff76a80-d2a1-4d36-b125-9e42d08fa019.png">

## Acceptance Criteria

- [ ] There is a new landingpage

## Tasks

- [ ] Create pages/landingpage
- [ ] create 4 buttons which navigate the User to the different pages
