### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#33]
## Value proposition

**As a** developer
**I need** a clean code
**to have** a good code structure

## Acceptance Criteria

- [ ] The length of the code is reduced and more efficient

## Tasks

- [ ] Look for unnecessary code
- [ ] Check/Update tests
- [ ] Check/Update storybook
- [ ] Check accessibility
