### ISSUE TITLE
settings update

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#34]
## Value proposition

**As a** User
**I need** more settings
**to be able to** produce a better sound

## Description
<img width="263" alt="Ohne Titel" src="https://user-images.githubusercontent.com/95469432/162427150-d396b589-e81a-4b96-8bb8-76deaf33a561.png">

## Acceptance Criteria

- [ ] There is a new volume control for the Sequencer

## Tasks

- [ ] Add volume control to Sequencer
- [ ] Update tests
- [ ] Update storybook
- [ ] Check accessibility
- [ ] Check on mobile device
