### ISSUE TITLE
sample upload

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#35]
## Value proposition

**As a** User
**I need** a sample upload
**to be able to** to play my own samples

## Description
<img width="252" alt="Bildschirmfoto 2022-03-28 um 10 53 00" src="https://user-images.githubusercontent.com/95469432/160362535-cab3e6c4-4fe1-4000-ade6-a8686c781617.png">

## Acceptance Criteria

- [ ] There is a new upload button
- [ ] The User is able to upload own samples

## Tasks

- [ ] Add Cloudinary to upload files
- [ ] Write/Update tests
