### ISSUE TITLE
DJ-Page

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#42]
## Value proposition

**As a** User
**I need** a DJ-Page
**to be able to** play music like a DJ

## Description
<img width="339" alt="Ohne Titel" src="https://user-images.githubusercontent.com/95469432/163979053-bc5b8948-4aca-4491-ba84-aacd2809801d.png">

## Acceptance Criteria

- [x] There is a new DJ-Page
- [x] There are 2 Tone.Player with 2 inputs to upload two files
- [x] There is a range input to fade between the two tracks

## Tasks

- [x] create -> pages/DJ-Page
- [x] create -> components/DJ-Player
- [x] Add range input
- [x] Add tests
- [x] Add Storybook
- [x] Check accessibility
- [x] Check on mobile device
