### ISSUE TITLE
dj-page filter

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#44]
## Value proposition

**As a** User
**I need** a filter, a eq3 and a cue-button for each Dj-Player 
**to be able to** mix more creative to the next song

## Acceptance Criteria

- [x] There is a new cue-button for each dj-deck
- [x] There are 3 inputs for the eq3
- [x] There is a filter for each dj-deck

## Tasks

- [x] Add cue buttons to DJPlayer
- [x] Create -> components/DJControls
     - [x] Add two eq3
     - [x] Add two filter
     - [x] Add tests
     - [x] Add storybook
- [x] Check on mobile device 
- [x] Check accessibility
