### ISSUE TITLE
player select on mobile device

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#46]
## Value proposition

**As a** User
**I need** only one dj-player visible (on mobile)
**to have** more space on my mobile screen

## Acceptance Criteria

- [x] On mobile there is only one dj-player visible
- [x] After click on a button the second dj-player is visible and the first is invisible

## Tasks

- [x] Add css to screen only one dj-player on mobile device
- [x] Add button to switch the players
- [x] Update tests
- [x] Check on mobile device
- [x] Check accessibility
