### ISSUE TITLE
pitch-fader

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#48]
## Value proposition

**As a** User
**I need** a pitch fader for my dj players
**to be able to** change the speed the track

## Acceptance Criteria

- [x] There is a new fader on each dj-player which changes the speed of the track

## Tasks

- [x] Add fader for each dj-player
- [x] Add functionality for the faders
- [x] Check on mobile device
- [x] Update tests
- [x] Check accessibility
