### ISSUE TITLE
echo-out

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#50]
## Value proposition

**As a** User
**I need** a echo effect
**to be able to** make creative transitions 

## Acceptance Criteria

- [ ] There is a new butten on each dj-player which triggers a delay effect

## Tasks

- [ ] Add a button with a delay functionality to each dj-player
- [ ] Update tests
- [ ] Check on mobile
- [ ] Check accessibility
