### ISSUE TITLE
Drum-Pad settings

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#6]
## Value proposition

**As a** User
**I need** a Settings-Page
**to be able to** change the colors of my Drum-Pads

## Description
![Bildschirmfoto 2022-03-07 um 15 17 07](https://user-images.githubusercontent.com/95469432/157051326-db05bfd9-89f1-4de9-a6e2-4bea906edc3f.png)

## Acceptance Criteria

- [x] The color of each button can be changed individually
- [x] There is a new settings page 

## Tasks

- [x] Add settings button on DrumMachinePage
- [x] Add React Router
- [x] Add global colors to globalstyles 
- [x] Create -> pages/SettingsPage
     - [x] Add back button to navigate back to DrumMachinePage
- [x] Create -> components/PadSettings
     - [x] Add dropdown menu with all Drum-Pads
     - [x] Add dropdown menu with prefilled colors
     - [x] Add save button to submit changes
     - [x] Add to SettingsPage
     - [x] Add Storybook
     - [x] Write tests
- [x] Update styling 
- [x] Add to App
- [x] Check accessibility
- [x] Check on mobile devices
