### ISSUE TITLE
Add-Sample-Select to settings

### ISSUE THREAD

**Issue by FaGru** [FaGru/capstone-project#7]
## Value proposition

**As a** User
**I need** a menu with prefilled samples
**to be able to** change the samples of the drum pads

## Description
<img width="329" alt="Bildschirmfoto 2022-03-09 um 16 05 11" src="https://user-images.githubusercontent.com/95469432/157468970-9f6d8d8e-f62a-49f5-93f6-ef6d8b5ad91f.png">

## Acceptance Criteria

- [x] There is a new dropdown menu to change the sample of a drum pad
- [x] The sample of each pad should be changeable 

## Tasks

- [x] Add dropdown menu to PadSettings
- [x] Add Samples
- [x] Write tests
- [x] Check accessibility
- [x] Check on mobile device
